# Generated by Django 5.2.6 on 2025-09-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_company_company_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyforjob',
            name='status',
            field=models.CharField(choices=[('new', 'New Applicant'), ('screening', 'Screening'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
    ]
