# Generated by Django 5.2.6 on 2025-10-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_applyforjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyforjob',
            name='ai_match_score',
            field=models.IntegerField(default=0, help_text='AI-calculated match score (0-100)'),
        ),
    ]
