# Generated by Django 5.2.3 on 2025-08-07 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userprofile_options_remove_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
