# Generated by Django 5.2.3 on 2025-08-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dateofbirth',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('company', 'Company'), ('applicant', 'Applicant')], default='applicant', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dateofbirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
