# Generated by Django 5.2.3 on 2025-08-09 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_customuser_dateofbirth_customuser_role_and_more'),
        ('jobs', '0002_applyforjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.company'),
        ),
    ]
