# Generated by Django 5.2.3 on 2025-08-09 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_company'),
        ('jobs', '0002_applyforjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='requested_company_name',
            field=models.CharField(blank=True, help_text='Only filled if requesting a new company', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='jobs.company'),
        ),
    ]
