# Generated by Django 5.2.3 on 2025-08-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_requested_company_name_customuser_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], help_text="Only applicable for users with 'Company' role", max_length=20, null=True),
        ),
    ]
