# Generated by Django 5.2.3 on 2025-08-10 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_customuser_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='requested_company_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='status',
        ),
    ]
